### ISSUE TITLE
Banco de Dados solicitados pela orientadora

### ISSUE THREAD

**Issue by Nayra-Reis** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e2-proj-int-t1-time2-aro#8]

**Comment by gabriellourenco12** [comment]
Banco de dados SQL Server criado. 
Dados para acesso:
- server name: pmv-ads-2023-1-e2-proj-int-t1-time2-aro.database.windows.net
- usuario: permita-se
- senha: P3rm!t4-se
